### PR TITLE
Added jhsmit as a maintainer.

### PR DESCRIPTION
**Pull request by tBuLi**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Add @Jhsmit as a maintainer for the conda repo.

### CODE REVIEW

**Comment by tBuLi** [comment]
@conda-forge-admin, please rerender

**Comment by tBuLi** [comment]
@conda-forge-admin, please rerender

**Comment by Jhsmit** [comment]
@conda-forge-admin, please update team

**Comment by Jhsmit** [comment]
Hi @conda-forge/core, we would like some assistance on this feedstock. We've tried to add me as a maintainer on this feedstock so that I can merge PR #6 in an attempt to update the feedstock for symfit release v0.5.1 but we're running into failed builds everywhere. Could you help out?

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender.

**Comment by ocefpaf** [comment]
Sometimes the webserices is down and a [local re-render is faster](https://conda-forge.org/docs/maintainer/updating_pkgs.html?#rerendering-with-conda-smithy-locally). I just did one in https://github.com/conda-forge/symfit-feedstock/pull/8

**Comment by ocefpaf** [comment]
Even though the re-render kick-in here let's go with #8 b/c I also updated the recipe there.

**Pull request closed without merging**
