### PR TITLE
Rerender

### PR DESCRIPTION
**Pull request by ocefpaf**
Alternative to #7

### CODE REVIEW

**Comment by ocefpaf** [comment]
Needs https://github.com/conda-forge/toposort-feedstock/pull/4

**Comment by Jhsmit** [comment]
@conda-forge-admin, please rerender

**Comment by Jhsmit** [comment]
Thanks for your help 👍

**Comment by ocefpaf** [comment]
> Thanks for your help

No problem. (I actually need this package today!)

**Pull request merged**
